CREATE TABLE xxhr_estructura_uteq (
    DIRE varchar(10) DEFAULT NULL,
    DEPT varchar(10) DEFAULT NULL,
    ORGANIZACION varchar(150) DEFAULT NULL,
    POS_NAME varchar(150) DEFAULT NULL,
    POS_STATUS varchar(20) DEFAULT NULL,
    JOB_NAME varchar(150) DEFAULT NULL,
    POS_TIPO_DESC varchar(80) DEFAULT NULL,
    POS_REF varchar(150) DEFAULT NULL,
    CATE_FED_ORIGINAL varchar(150) DEFAULT NULL,
    CAT_FED varchar(150) DEFAULT NULL,
    SDO_FED decimal(10, 2) DEFAULT NULL,
    GPO_FED varchar(150) DEFAULT NULL,
    HRS_FED varchar(25) DEFAULT NULL,
    EMP_NUM varchar(25) NOT NULL,
    EMP_NAME varchar(150) DEFAULT NULL,
    EMP_CURP varchar(20) DEFAULT NULL,
    EMP_RFC varchar(20) DEFAULT NULL,
    EMP_IMSS varchar(20) DEFAULT NULL,
    EMP_SEX varchar(5) DEFAULT NULL,
    EMP_AGE int(150) DEFAULT NULL,
    EMP_PRI_CON date DEFAULT NULL,
    ASG_INI date DEFAULT NULL,
    ASG_FIN date DEFAULT NULL,
    ASG_NUM varchar(20) DEFAULT NULL,
    ASG_SIN varchar(5) DEFAULT NULL,
    SINDICALIZADO_N_S varchar(5) DEFAULT NULL,
    ASG_TIPO_CONTRATO varchar(8) DEFAULT NULL,
    TIPO_CONTRATO varchar(25) DEFAULT NULL,
    ASG_SDO decimal(10, 2) DEFAULT NULL,
    ASG_SDO_FEC date DEFAULT NULL,
    ASG_HOR int(8) DEFAULT NULL,
    NOM_ID_1 varchar(8) DEFAULT NULL,
    NOM_NAME_1 varchar(20) DEFAULT NULL,
    BASE_NAME_1 varchar(20) DEFAULT NULL,
    ASG_REF varchar(150) DEFAULT NULL,
    EMAIL varchar(150) DEFAULT NULL,
    QUINQUENIO varchar(5) DEFAULT NULL,
    EMP_ACT_CON date DEFAULT NULL,
    EMP_BIRTHDATE date DEFAULT NULL,
    MARITAL_ESTATUS varchar(255) DEFAULT NULL,
    PASSWORD varchar(255) DEFAULT NULL,
    ESTATUS varchar(5) DEFAULT NULL
);
CREATE TABLE xxhr_estructura_historial_uteq (
    ID_HISTORIAL int(10) AUTO_INCREMENT ,
    FECHA date DEFAULT NULL,
    DIRE varchar(10) DEFAULT NULL,
    DEPT varchar(10) DEFAULT NULL,
    ORGANIZACION varchar(150) DEFAULT NULL,
    POS_NAME varchar(150) DEFAULT NULL,
    POS_STATUS varchar(20) DEFAULT NULL,
    JOB_NAME varchar(150) DEFAULT NULL,
    POS_TIPO_DESC varchar(80) DEFAULT NULL,
    POS_REF varchar(150) DEFAULT NULL,
    CATE_FED_ORIGINAL varchar(150) DEFAULT NULL,
    CAT_FED varchar(150) DEFAULT NULL,
    SDO_FED decimal(10, 2) DEFAULT NULL,
    GPO_FED varchar(150) DEFAULT NULL,
    HRS_FED varchar(25) DEFAULT NULL,
    EMP_NUM varchar(25) NOT NULL,
    EMP_NAME varchar(150) DEFAULT NULL,
    EMP_CURP varchar(20) DEFAULT NULL,
    EMP_RFC varchar(20) DEFAULT NULL,
    EMP_IMSS varchar(20) DEFAULT NULL,
    EMP_SEX varchar(5) DEFAULT NULL,
    EMP_AGE int(150) DEFAULT NULL,
    EMP_PRI_CON date DEFAULT NULL,
    ASG_INI date DEFAULT NULL,
    ASG_FIN date DEFAULT NULL,
    ASG_NUM varchar(20) DEFAULT NULL,
    ASG_SIN varchar(5) DEFAULT NULL,
    SINDICALIZADO_N_S varchar(5) DEFAULT NULL,
    ASG_TIPO_CONTRATO varchar(8) DEFAULT NULL,
    TIPO_CONTRATO varchar(25) DEFAULT NULL,
    ASG_SDO decimal(10, 2) DEFAULT NULL,
    ASG_SDO_FEC date DEFAULT NULL,
    ASG_HOR int(8) DEFAULT NULL,
    NOM_ID_1 varchar(8) DEFAULT NULL,
    NOM_NAME_1 varchar(20) DEFAULT NULL,
    BASE_NAME_1 varchar(20) DEFAULT NULL,
    ASG_REF varchar(150) DEFAULT NULL,
    EMAIL varchar(150) DEFAULT NULL,
    QUINQUENIO varchar(5) DEFAULT NULL,
    EMP_ACT_CON date DEFAULT NULL,
    EMP_BIRTHDATE date DEFAULT NULL,
    MARITAL_ESTATUS varchar(255) DEFAULT NULL,
    PASSWORD varchar(255) DEFAULT NULL,
    ESTATUS varchar(5) DEFAULT NULL
);
CREATE TABLE xxhr_menu (
    ID_MENU INT(15) AUTO_INCREMENT PRIMARY KEY,
    NAME_MENU VARCHAR(100) NOT NULL,
    ESTATUS varchar(5) DEFAULT NULL
);
CREATE TABLE xxhr_submenu (
    ID_SUBMENU INT(15) AUTO_INCREMENT PRIMARY KEY,
    NAME_SUBMENU VARCHAR(100) NOT NULL,
    ESTATUS varchar(5) DEFAULT NULL
);
CREATE TABLE xxhr_menu_submenu (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMP_NUM varchar(25) NOT NULL,
    MENU_ID INT(15) NOT NULL,
    SUBMENU_ID INT(15) NOT NULL,
    FOREIGN KEY (MENU_ID) REFERENCES menu(ID_MENU),
    FOREIGN KEY (SUBMENU_ID) REFERENCES submenu(ID_SUBMENU)
);
CREATE TABLE xxhr_mando(
    ID_MANDO int(10) AUTO_INCREMENT PRIMARY KEY,
    NUM_MANDO VARCHAR(5) DEFAULT NULL,
    ESTATUS_MANDO VARCHAR(2) DEFAULT NULL
);
CREATE TABLE xxhr_imagenes(
    ID_IMAGEN int(5) AUTO_INCREMENT PRIMARY KEY,
    IMG VARCHAR(20) DEFAULT NULL,
    ACTION VARCHAR(2) DEFAULT NULL
);
------------------------------------------------------
create table xxhr_direcciones(
    ID_DIRECCION int(5) AUTO_INCREMENT PRIMARY KEY,
    CODIGO VARCHAR(20) DEFAULT NULL,
    DESCRIPCION VARCHAR(100)
);
create table xxhr_departamentos(
    ID_DEPARTAMENTO int(5) AUTO_INCREMENT PRIMARY KEY,
    CODIGO VARCHAR(20) DEFAULT NULL,
    DESCRIPCION VARCHAR(100) DEFAULT NULL
);

CREATE table xxhr_aprobacion(
    ID_APROBACION int(5) AUTO_INCREMENT PRIMARY KEY,
    EMP_NUM_MANDO varchar(25) DEFAULT NULL,
    EMP_NUM varchar(25) DEFAULT NULL,
    ESTATUS varchar(5) DEFAULT NULL
);





---------------------------------------------------------
ALTER TABLE xxhr_estructura_historial_uteq
ADD CONSTRAINT fk_historial FOREIGN KEY (EMP_NUM) REFERENCES xxhr_estructura_uteq (EMP_NUM);
-------------------ADD PRIMARY KEY-----------------------
ALTER TABLE xxhr_estructura_historial_uteq
ADD KEY ID_HISTORIAL (ID_HISTORIAL);

ALTER TABLE xxhr_estructura_historial_uteq
ADD CONSTRAINT historial_ibfk_1 FOREIGN KEY (EMP_NUM) REFERENCES xxhr_estructura_uteq (EMP_NUM);


ALTER TABLE xxhr_estructura_historial_uteq
MODIFY ID_HISTORIAL int(10) AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE xxhr_estructura_uteq
MODIFY ESTATUS varchar(5) DEFAULT NULL;


RENAME TABLE mando TO xxhr_mando;